/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package serveasestart;

import javax.swing.JOptionPane;
import serveasestart.CustomerLoginScreen;
import serveasestart.AccountScreen;
import serveasestart.Customer;

/**
 *
 * @author User
 */
public class CustomerHomeScreen extends javax.swing.JFrame {
   private Customer customer;
    /**
     * Creates new form CustomerHomeScreen
     */
     public CustomerHomeScreen(Customer customer) {
        this.customer = customer;
        initComponents();
        jLabel1.setText("Welcome, " + customer.getFirstName() + " " + customer.getLastName());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReserveTablebt = new javax.swing.JButton();
        ViewMenubt = new javax.swing.JButton();
        MyAccountbt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ReserveTablebt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ReserveTablebt.setText("Reserve Table");
        ReserveTablebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveTablebtActionPerformed(evt);
            }
        });

        ViewMenubt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ViewMenubt.setText("View Menu");
        ViewMenubt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMenubtActionPerformed(evt);
            }
        });

        MyAccountbt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MyAccountbt.setText("My Account");
        MyAccountbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyAccountbtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel1.setText("Welcome, dear Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(MyAccountbt)
                    .addComponent(ViewMenubt)
                    .addComponent(ReserveTablebt))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(ReserveTablebt)
                .addGap(18, 18, 18)
                .addComponent(ViewMenubt)
                .addGap(18, 18, 18)
                .addComponent(MyAccountbt)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewMenubtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMenubtActionPerformed
        // TODO add your handling code here:
        MenuScreen ms = new MenuScreen (customer);
        ms.setVisible(true);
        
        dispose ();
    }//GEN-LAST:event_ViewMenubtActionPerformed

    private void ReserveTablebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveTablebtActionPerformed
        // TODO add your handling code here:
        TableReservationScreen trs = new TableReservationScreen ();
        trs.show();
        
        dispose ();
    }//GEN-LAST:event_ReserveTablebtActionPerformed

    private void MyAccountbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyAccountbtActionPerformed
       // TODO add your handling code here:
     new AccountScreen(customer).setVisible(true);
        dispose();

        dispose ();
    }//GEN-LAST:event_MyAccountbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MyAccountbt;
    private javax.swing.JButton ReserveTablebt;
    private javax.swing.JButton ViewMenubt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
