/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package serveasestart;
import javax.swing.JOptionPane; 
import serveasestart.Customer;
import serveasestart.RoomCharge;

/**
 *
 * @author User
 */    
    /**
     * Creates new form RoomChargeScreen
     */
    public class RoomChargeScreen extends javax.swing.JFrame {
    private Customer customer;
    
    public RoomChargeScreen(Customer customer) {
       this.customer = customer;
       initComponents();
       loadCustomerRoomChargeDetails();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RoomChargeEnablebt = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        CreditLimit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Backbt = new javax.swing.JButton();
        SaveChangesbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Press the button to enable Room Charge");

        RoomChargeEnablebt.setText("Room Charge");
        RoomChargeEnablebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomChargeEnablebtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Set your credit limit");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel3.setText("Room Charge");

        Backbt.setText("Back");
        Backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtActionPerformed(evt);
            }
        });

        SaveChangesbt.setText("Save Changes");
        SaveChangesbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveChangesbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(RoomChargeEnablebt)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(102, 102, 102)
                        .addComponent(Backbt))
                    .addComponent(CreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveChangesbt))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Backbt))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoomChargeEnablebt)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(SaveChangesbt)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtActionPerformed
        // TODO add your handling code here:
        new AccountScreen(customer).setVisible(true);
        dispose();
        
        dispose ();
    }//GEN-LAST:event_BackbtActionPerformed

    private void SaveChangesbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveChangesbtActionPerformed
        // TODO add your handling code here:
        boolean cardProvided = RoomChargeEnablebt.isSelected();
        double creditLimit = Double.parseDouble(CreditLimit.getText());
        String roomNumber = String.valueOf(customer.getRoomNumber());

        RoomCharge roomCharge = new RoomCharge(cardProvided, creditLimit, roomNumber);
        customer.activateRoomCharge(roomCharge);
        JOptionPane.showMessageDialog(this, "Room charge settings saved successfully!");
        
    }//GEN-LAST:event_SaveChangesbtActionPerformed

    private void RoomChargeEnablebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomChargeEnablebtActionPerformed
      boolean cardProvided = RoomChargeEnablebt.isSelected();
    double creditLimit = Double.parseDouble(CreditLimit.getText());
    String roomNumber = String.valueOf(customer.getRoomNumber());

    RoomCharge roomCharge = new RoomCharge(cardProvided, creditLimit, roomNumber);
    customer.activateRoomCharge(roomCharge);
    JOptionPane.showMessageDialog(this, "Room charge settings saved successfully!");
    }//GEN-LAST:event_RoomChargeEnablebtActionPerformed
    
    
    private void loadCustomerRoomChargeDetails() {
    RoomCharge roomCharge = customer.getRoomCharge();
    if (roomCharge != null) {
        RoomChargeEnablebt.setSelected(roomCharge.isCardProvided());
        CreditLimit.setText(String.valueOf(roomCharge.getCreditLimit()));
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomChargeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomChargeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomChargeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomChargeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            // Create a sample Customer object for testing
            Customer customer = new Customer("c201", "dgrimanis", "Damianos", "Grimanis", "grimanis101", "2024-5-12","2024-5-20",106);
            new RoomChargeScreen(customer).setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbt;
    private javax.swing.JTextField CreditLimit;
    private javax.swing.JToggleButton RoomChargeEnablebt;
    private javax.swing.JButton SaveChangesbt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
